services:
  app:
    build:
      context: ./appprueba
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      MONGO_URI: ${MONGO_URI}
    command: ["node", "index.js"]
